### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mattgwwalker** [r0fls/swiftstats#11]
The current code lacks documentation, especially user-focused documentation.

**Comment by mattgwwalker** [comment]
I've added a lot of documentation for the Common functions and used Jazzy to automatically generate HTML documentation.  @r0fls would you mind setting up the project so that GitHub Pages is enabled on the master/docs directory?  I don't have the rights to make that change.

**Comment by r0fls** [comment]
Whoops, sorry for the delay. Docs look great! http://r0fls.github.io/swiftstats/
