### ISSUE TITLE
Poisson distribution pmf function

### ISSUE THREAD

**Issue by kupinski** [r0fls/swiftstats#24]
The Poisson distribution probability mass function needs to be updated.  The current version uses:
return pow(self.m, Double(k))*exp(-self.m)/tgamma(Double(k+1))
which is numerically unstable for large m.  This causes the Poisson random numbers to stop working with an m larger that 15 or so.

A better choice is to use:
return exp(Double(k) * log(m) - m - lgamma(Double(k+1)))
which is numerically stable up to large m.  The use of the lgamma function (log gamma) and getting rid of the power makes this far easier to compute.

**Comment by mattgwwalker** [comment]
Thanks @kupinski, that was a very useful contribution.

I've added tests that demonstrated the issue you highlighted.  With your suggested modification, we are now passing those tests.

I'll close this issue, but if there are any problems, please feel free to re-open it.

Thanks again.

Matthew

Tests added:

        // Issue #24: Poisson unstable at large values of m
        // Test for small values of m
        /* R code:
            > dpois(2,3)
            [1] 0.2240418
         */
        let p3 = SwiftStats.Distributions.Poisson(m: 3)
        XCTAssert(abs(p3.pmf(2) - 0.2240418) < epsilon)
        
        // Test for large values of m (m > 15)
        /* R code:
            > dpois(29,30)
            [1] 0.07263453
         */
        let p4 = SwiftStats.Distributions.Poisson(m: 30)
        XCTAssert(abs(p4.pmf(29) - 0.07263453) < epsilon)
        
        // Test for very large values of m
        /* R code:
            > dpois(290,300)
            [1] 0.01978727
        */
        let p5 = SwiftStats.Distributions.Poisson(m: 300)
        XCTAssert(abs(p5.pmf(290) - 0.01978727) < epsilon)
