### ISSUE TITLE
Fix Travis CI tests

### ISSUE THREAD

**Issue by r0fls** [r0fls/swiftstats#3]
There are unit tests already, but we should enable Travis CI. I did this a few years ago and there was some issue. We'll have to re-enable them now to see if there is still a problem.

**Comment by r0fls** [comment]
Here's the old travis build log for reference: https://travis-ci.org/r0fls/swiftstats

I'm going to try running it with swift 4.2

**Comment by mattgwwalker** [comment]
Wow, that is some significant series of errors.  And some of them are truly strange, like complaining about an underscore in the method name.  Where in GitHub to you look to test the tester? ;o)

**Comment by mattgwwalker** [comment]
![screen shot 2018-11-30 at 10 39 00 pm](https://user-images.githubusercontent.com/4054492/49281187-c89f1f80-f4f0-11e8-8863-4a49d7ec917a.png)

Travis testing is now passing!

All that was required was to bring the xcode version up in the .travis.yml file.  The current version is 10.1, so I chose that and now all works well.
