### ISSUE TITLE
Initial capitalisation

### ISSUE THREAD

**Issue by mattgwwalker** [r0fls/swiftstats#5]
I noted very early on that this library uses methods where the initial letter is capitalised.  I also see that the documentation often refers (currently incorrectly) to methods with lower case initial letters.

Given that the standard library methods use lower case initial letters, would you mind if I updated this library to be the same as Swift's standard libraries?

This would mean that "Random" would become "random", for example.  A total of four method names would be impacted: Random, Pdf, Cdf, and Quantile.

**Comment by r0fls** [comment]
Sounds great, please do

**Comment by mattgwwalker** [comment]
I've made these changes, and I was about to create a pull request, but I realised I based the changes to top of the work I did adding the log-normal distribution.

I guess the best thing is for me to to wait for you to go through my log-normal pull request and then create a new pull request for this change of case story.  As you can tell, this collaborative git thing is new for me :o)

**Comment by r0fls** [comment]
Ah ha, yes you can do that, or you can create a new branch _from master_, then cherry-pick the commits that you want from the other branch. This would look something like:

```
git checkout master
git pull # to make sure you're up to date
git checkout -b initial-capitalisation
git cherry-pick <COMMIT-HASH1> <COMMIT-HASH2> ...
```

Where `<COMMIT-HASH1>` is the first commit from your lognormal branch that you want to take, with the initial capitalisation changes, etc...


Or, just wait, up to you

**Comment by r0fls** [comment]
After that you would push your new branch to your remote and create a PR from that:

```
git push -u origin initial-capitalisation
```
